In [3]:
import numpy as np
from os.path import join
from glob import glob

In [36]:
train_val_npy_path = [
    '/home/gennosuke/logs/magicpoint_ms_coco_akaze/predictions/train/*',
    '/home/gennosuke/logs/magicpoint_ms_coco_akaze/predictions/val/*'
]
for npy_path in train_val_npy_path:
    path_list = glob(npy_path)
    for path in path_list[:]:
        labels = np.zeros((240, 320))
        npy = np.load(path)
        pnts = npy['pts']
        pnts = pnts.astype(int)
        try:
            labels[pnts[:, 1], pnts[:, 0]] = 1
        except IndexError as e:
            print(path)

/home/gennosuke/logs/magicpoint_ms_coco_akaze/predictions/train/COCO_train2014_000000357272.npz
/home/gennosuke/logs/magicpoint_ms_coco_akaze/predictions/train/COCO_train2014_000000148931.npz


In [71]:
error_npy_path = [
    '/home/gennosuke/logs/magicpoint_ms_coco_akaze/predictions/train/COCO_train2014_000000357272.npz',
    '/home/gennosuke/logs/magicpoint_ms_coco_akaze/predictions/train/COCO_train2014_000000148931.npz'
]
import os
for ep in error_npy_path[:]:
    error_npy_file = np.load(ep)
    npz = error_npy_file['pts']
    new_array = []
    for n in npz:
        if np.isnan(n[0]) or np.isnan(n[1]):
            continue
        else:
            new_array.append(n)
    new_array = np.array(new_array)
    np.savez(os.path.basename(ep), pts=new_array)

In [74]:
new_npz1 = np.load('./COCO_train2014_000000148931.npz')
print(new_npz1.files)
print(new_npz1['pts'])
new_npz1 = np.load('./COCO_train2014_000000357272.npz')
print(new_npz1.files)
print(new_npz1['pts'])

['pts']
[[6.4785849571228027e+01 1.7205400204658508e+02 1.5540933609008789e-01]
 [2.7977672398090363e+02 1.6015590476989746e+02 1.3609521090984344e-01]
 [1.1414777922630310e+02 1.4794986999034882e+02 1.2316425144672394e-01]
 [2.3508576941490173e+02 1.5816551828384399e+02 1.2273446470499039e-01]
 [2.2360643625259399e+02 8.9999348878860474e+01 1.1992271244525909e-01]
 [2.9630076694488525e+02 8.2854097485542297e+01 1.1882293969392776e-01]
 [2.1570711374282837e+02 1.1124306321144104e+02 1.1628898978233337e-01]
 [1.3611247158050537e+02 1.4694063186645508e+02 1.1488243192434311e-01]
 [2.3293065440654755e+02 1.4202488899230957e+01 1.0768357664346695e-01]
 [2.9196373140811920e+02 6.9876568198204041e+01 1.0525687783956528e-01]
 [2.9125939702987671e+02 4.4984238386154175e+01 1.0499652475118637e-01]
 [2.8086160933971405e+02 1.4362860679626465e+02 1.0403346270322800e-01]
 [1.1111103224754333e+02 1.6797684597969055e+02 1.0184832662343979e-01]
 [1.1058351385593414e+02 1.0599092686176300e+02 1.013517